service: api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-localstack
  - serverless-offline
  
custom:
  localstack:
    stages: local
    host: http://localhost
    edgePort: 4566

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
